
name: 'helmauto'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'helm'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash


    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Setup helm
      run: sudo snap install helm --classic


   
    - name: Add repo helm
      run: helm repo add mytesthelm https://manelOyez.github.io/helmtest/

    - name: Test if repo is here
      run: helm serach repo mytesthelm 

    
